### ISSUE TITLE
Display the detected fault list at the end of the simulation

### ISSUE THREAD

**Issue by MaineK00n** [ehimetakahashilab/Logic-BIST-Sim#2]

**Comment by senlingwang** [comment]
a fault detection table wiill be outputed to the home directory, at the end of simulation.  First column denotes the fault number, second column denotes the fault detection (=1, detected, =0, undetected ) by the multicycle test (or scan test). if you chose multi-cycle test with OPI or CPI, the fault detection by OPI or CPI will be output following the second column, in such case, the last column will be the fault detection by full obervation. e.g.: multi-cycle test with SEQ-OB by TOPISIS, MIN,COP selection, the output of fault table will be, fault number, detection of multi-cycle test , detection of SEQ-OB with TOPSIS, MIN, COP, detection of SEQ-OB by Full-observation.

**Comment by MaineK00n** [comment]
@senlingwang 

Please close this issue if it is fully supported.
